Repository SUSE/caasp-release-notes, pull requests merged in 2020-04, with the labels that each got.

#38 Add note about new vmware datastore cluster var
  adoc/MAIN.release-notes.adoc
Labels: 4.2.0

#45 release-velero: add changes in release-velero: disaster and recovery
  adoc/MAIN.release-notes.adoc
Labels: 4.1.2

#52 Add note about IAM profiles for AWS via CLI
  adoc/MAIN.release-notes.adoc
Labels: 4.2.0, On-Hold

#48 Add k8s 1.17 release notes to 4.2.0
  adoc/MAIN.release-notes.adoc
Labels: 4.2.0

#49 Add known bug when upgrading to 1.17 regarding a conflict with cri-o
  adoc/MAIN.release-notes.adoc
Labels: 4.2.0
